model_opts:
  model: MASK_PCPA_2D
  obs_input_type: [local_context_cnn, mask_cnn, pose, box, speed]
  apply_class_weights: True
  normalize_boxes: True
  generator: True
net_opts:
  num_hidden_units: 256
  global_pooling: avg
  regularizer_val: 0.0001
  cell_type: gru
  backbone: vgg
exp_opts:
  datasets: [jaad_beh, jaad_all]
  batch_size: [2, 2]
  epochs: [40, 40]
  lr: [5.0e-07, 5e-07]
