model_opts:
  model: PCPA
  obs_input_type: [local_context, pose, box, speed]
  apply_class_weights: True
  normalize_boxes: True
  generator: True
net_opts:
  num_hidden_units: 256
  global_pooling: avg
  regularizer_val: 0.0001
  cell_type: gru
  backbone: c3d
exp_opts:
  datasets: [pie]
  batch_size: [2]
  epochs: [60]
  lr: [5.0e-05]

